const data = {
  dataScience: [
    {
      id: 10,
      img: "https://coursemarks.com/wp-content/uploads/2020/11/2894606_ef6e.jpg",
      name: " Machine learning from A_Z ",
      instru: "james john",
      views: "1320",
      text: "Learn data science with from zero to hero and change the future",
      price: "130",
      priceValue: "130-240",
    },
    {
      id: 2,
      img: "https://img-c.udemycdn.com/course/240x135/629302_8a2d_2.jpg",
      name: "Python for data science and machine learning bootcamp ",
      instru: "james zaki",
      views: "3100",
      text: "Learn data science with from zero to hero and change the future",
      price: "90",
      priceValue: "40-120",
    },
    {
      id: 3,
      img: "https://img-c.udemycdn.com/course/240x135/713104_d4cb.jpg",
      name: " AI artificial intellegence",
      instru: "ahmed shokair",
      views: "2000",
      text: "Learn data science with from zero to hero and change the future",
      price: "400",
      priceValue: "250-500",
    },
    {
      id: 4,
      img: "https://img-c.udemycdn.com/course/240x135/903744_8eb2.jpg",
      name: " real life data science exercises  ",
      instru: "mohammed nadir",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "90",
      priceValue: "40-120",
    },
    {
      id: 5,
      img: "https://img-c.udemycdn.com/course/240x135/713104_d4cb.jpg",
      name: " satisticis for data science  ",
      instru: "mohamed ali",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "40",
      priceValue: "40-120",
    },
    {
      id: 6,
      img: "https://coursemarks.com/wp-content/uploads/2020/11/2894606_ef6e.jpg",
      name: " machine learning basics",
      instru: "khalid jamal",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "280",
      priceValue: "250-500",
    },
    {
      id: 7,
      img: "https://img-c.udemycdn.com/course/240x135/2776760_f176_6.jpg",
      name: "nodejs and vuejs",
      instru: "Mustafa barzan",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "130",
      priceValue: "130-240",
    },
    {
      id: 8,
      img: "https://img-c.udemycdn.com/course/240x135/629302_8a2d_2.jpg",
      name: " complete data science ...",
      instru: "khalid jamal",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "300",
      priceValue: "250-500",
    },
    {
      id: 9,
      img: "https://coursemarks.com/wp-content/uploads/2020/11/2894606_ef6e.jpg",
      name: " design machines with new technical",
      instru: "Mustafa barzan",
      views: "1200",
      text: "Learn data science with from zero to hero and change the future",
      price: "210",
      priceValue: "130-240",
    },
  ],
};

export default data;
