const data = {
  MobileData: [
    {
      id: 1,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4V-pJsd5W_NzcJT1hd20RcaS1fMVG_YNycA&usqp=CAU",
      name: "beginner flutter course  ",
      instru: "james john",
      views: "1320",
      text: "  Learn mobile development with professional teachers",
      price: "130",
      priceValue: "91-150",
    },
    {
      id: 2,
      img: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.perforce.com%2Fblog%2Fvcs%2Ffuture-of-game-development-trends&psig=AOvVaw08Bp-8btzIUTi8zosDzTYD&ust=1638977867604000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCMCSp8GC0vQCFQAAAAAdAAAAABAO",
      name: "advanced flutter course",
      instru: "james zaki",
      views: "3100",
      text: "  Learn mobile development with professional teachers",
      price: "250",
      priceValue: "151-300",
    },
    {
      id: 3,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsu0IopyOcmdwlg1MLoZLLqXbAhPLbuiJrKg&usqp=CAU",
      name: " react native ",
      instru: "osama elzero",
      views: "2000",
      text: "  Learn mobile development with professional teachers",
      price: "120",
      priceValue: "91-150",
    },
    {
      id: 4,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4V-pJsd5W_NzcJT1hd20RcaS1fMVG_YNycA&usqp=CAU",
      name: "backend infrastructure ",
      instru: "abdulrahman sami",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "200",
      priceValue: "151-300",
    },
    {
      id: 5,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8HnI9rhiXDb1yTcQMdPT07mYBXP2Iej_MkA&usqp=CAU",
      name: "flutter course",
      instru: "mohamed ali",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "90",
      priceValue: "40-90",
    },
    {
      id: 6,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4V-pJsd5W_NzcJT1hd20RcaS1fMVG_YNycA&usqp=CAU",
      name: "HTMLl5",
      instru: "khalid jamal",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "40",
      priceValue: "40-90",
    },
    {
      id: 7,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5gEb4iP9C1bKLIja2jWBzkys3JoMW9g8Tjw&usqp=CAU",
      name: "mobile development advanced course",
      instru: "Mustafa barzan",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "190",
      priceValue: "91-150",
    },
    {
      id: 8,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsu0IopyOcmdwlg1MLoZLLqXbAhPLbuiJrKg&usqp=CAU",
      name: " UI / UX Design",
      instru: "menna ali",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "60",
      priceValue: "40-90",
    },
    {
      id: 9,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5gEb4iP9C1bKLIja2jWBzkys3JoMW9g8Tjw&usqp=CAU",
      name: "Mobile App Front-Ende",
      instru: "Mustafa barzan",
      views: "1200",
      text: "  Learn mobile development with professional teachers",
      price: "90",
      priceValue: "40-90",
    },
  ],
};

export default data;
